### ISSUE TITLE
Can you release official implementation?

### ISSUE THREAD

**Issue by Mikey12SHTech** [KumapowerLIU/Rethinking-Inpainting-MEDFE#1]
Your work is amazing and would you release the code?

**Comment by KumapowerLIU** [comment]
of course. coming soon!

**Comment by crazygirl1992** [comment]
hello,your work is great and could you open your code ? waitting online

**Comment by ranjiewwen** [comment]
waiting for

**Comment by FiftyWu** [comment]
waiting for

**Comment by junleen** [comment]
Have been waiting for the great code for two months:)
