### ISSUE TITLE
Test code

### ISSUE THREAD

**Issue by roooooz** [KumapowerLIU/Rethinking-Inpainting-MEDFE#5]
Your work is very helpful to me. But i can't find the test code and when the test code will be released?

**Comment by KumapowerLIU** [comment]
I'm on vacation since the last few days are National Day in china. The test code will be released soon.

**Comment by zengxianyu** [comment]
I wrote a test script for this code. Could you please help to check is it correctly using the model? 

https://github.com/zengxianyu/Rethinking-Inpainting-MEDFE/blob/master/test.py
